# core/field_mappings.py
common_names= {
    "imo": "imo",
    "mmsi": "mmsi",
    "flag": "flag",
    "call_sign": "call_sign",
    "dwt": "dwt",
    "gt": "gt",
    "status": "status",
    "navigation_status": "navigation_status",
    "ais_type": "ais_type",
    "draught": "draught",
    "speed": "speed",
    "max_speed": "max_speed",
    "avg_speed": "avg_speed",
    "max_wind": "max_wind",
    "avg_wind": "avg_wind",
    "min_wind": "min_wind",
    "min_temp": "min_temp",
    "max_temp": "max_temp",
    "eta": "eta",
    "course": "course",
    "source": "source",
    "destination": "destination",
    "position_received": "position_received",
    "lat_long": "latitude_longitude",
    "latitude": "latitude",
    "longitude": "longitude",
    "area": "area",
    "build": "build",
    "distance": "distance",
}

FIELD_MAPPINGS = {
    "myship": {
        # Newly added from table-sm
        "IMO": common_names["imo"],
        "MMSI": common_names["mmsi"],
        "Flag": common_names["flag"],
        "Call Sign": common_names["call_sign"],
        "DWT": common_names["dwt"],
        "GT": common_names["gt"],
        "Draught": common_names['draught'],
        "Position Received": common_names['position_received'],
        "Longitude": common_names['longitude'],
        "Latitude": common_names['latitude'],
        "Status": common_names['status'],
        "Speed": common_names['speed'],
        "AVG Speed": common_names['avg_speed'],
        "MAX Speed": common_names['max_speed'],
        "Course": common_names['course'],
        "Area": common_names['area'],
        "Build": common_names['build'],
        "AVG Wind": common_names['avg_wind'],
        "MAX Wind": common_names['max_wind'],
        "MIN Temp": common_names['min_temp'],
        "MAX Temp": common_names['max_temp'],
        "Distance Travelled": common_names['distance'],
        "Remaining Time": common_names['eta'],
    },

    "vesselfinder": {
        "IMO / MMSI": common_names['imo'],
        "Callsign": common_names["call_sign"],
        "AIS Flag": common_names['flag'],
        "Course / Speed": common_names['speed'],
        "Navigation Status": common_names['navigation_status'],
        "Current draught": common_names['draught'],
        "Position Received": common_names['position_received'],
        "Destination": common_names['destination'],
        "Predicted ETA": common_names['eta'],
        "Area": common_names['area'],
        "Latitude / Longitude": common_names['lat_long'],
        "AIS Type": common_names['ais_type'],
        "Distance / Time": common_names['distance'],
    },

    "vesseltracker": {
        "IMO": common_names["imo"],
        "MMSI": common_names["mmsi"],
        "Flag": common_names["flag"],
        "Callsign": common_names["call_sign"],
        "AIS type": common_names['ais_type'],
        "Deadweight": common_names['dwt'],
        "Gross tonnage": common_names["gt"],
        "Year of build": common_names["build"],
        "Navigational status": common_names['navigation_status'],
        "Course": common_names['course'],
        "Speed": common_names['speed'],
        "MAX Speed": common_names['max_speed'],
        "Area": common_names['area'],
        "ETA": common_names['eta'],
        "Source": common_names['source'],
        "Destination": common_names['destination'],
        "Position": common_names['position_received'],
        "Status": common_names['status'],
    }
    
}
