# core/field_mappings.py
COMMON_NAMES = {
    "imo": "imo",
    "mmsi": "mmsi",
    "flag": "flag",
    "call_sign": "call_sign",
    "dwt": "dwt",
    "gt": "gt",
    "status": "status",
    "navigation_status": "navigation_status",
    "ais_type": "ais_type",
    "draught": "draught",
    "speed": "speed",
    "max_speed": "max_speed",
    "avg_speed": "avg_speed",
    "max_wind": "max_wind",
    "avg_wind": "avg_wind",
    "min_wind": "min_wind",
    "min_temp": "min_temp",
    "max_temp": "max_temp",
    "eta": "eta",
    "course": "course",
    "source": "source",
    "destination": "destination",
    "position_received": "position_received",
    "lat_long": "latitude_longitude",
    "latitude": "latitude",
    "longitude": "longitude",
    "area": "area",
    "build": "build",
    "distance": "distance",
}

FIELD_MAPPINGS = {
    "myship": {
        # Newly added from table-sm
        "IMO": COMMON_NAMES["imo"],
        "MMSI": COMMON_NAMES["mmsi"],
        "Flag": COMMON_NAMES["flag"],
        "Call Sign": COMMON_NAMES["call_sign"],
        "DWT": COMMON_NAMES["dwt"],
        "GT": COMMON_NAMES["gt"],
        "Draught": COMMON_NAMES['draught'],
        "Position Received": COMMON_NAMES['position_received'],
        "Longitude": COMMON_NAMES['longitude'],
        "Latitude": COMMON_NAMES['latitude'],
        "Status": COMMON_NAMES['status'],
        "Speed": COMMON_NAMES['speed'],
        "AVG Speed": COMMON_NAMES['avg_speed'],
        "MAX Speed": COMMON_NAMES['max_speed'],
        "Course": COMMON_NAMES['course'],
        "Area": COMMON_NAMES['area'],
        "Build": COMMON_NAMES['build'],
        "AVG Wind": COMMON_NAMES['avg_wind'],
        "MAX Wind": COMMON_NAMES['max_wind'],
        "MIN Temp": COMMON_NAMES['min_temp'],
        "MAX Temp": COMMON_NAMES['max_temp'],
        "Distance Travelled": COMMON_NAMES['distance'],
        "Remaining Time": COMMON_NAMES['eta'],
    },

    "vesselfinder": {
        "IMO / MMSI": COMMON_NAMES['imo'],
        "Callsign": COMMON_NAMES["call_sign"],
        "AIS Flag": COMMON_NAMES['flag'],
        "Course / Speed": COMMON_NAMES['speed'],
        "Navigation Status": COMMON_NAMES['navigation_status'],
        "Current draught": COMMON_NAMES['draught'],
        "Position Received": COMMON_NAMES['position_received'],
        "Destination": COMMON_NAMES['destination'],
        "Predicted ETA": COMMON_NAMES['eta'],
        "Area": COMMON_NAMES['area'],
        "Latitude / Longitude": COMMON_NAMES['lat_long'],
        "AIS Type": COMMON_NAMES['ais_type'],
        "Distance / Time": COMMON_NAMES['distance'],
    },

    "vesseltracker": {
        "IMO": COMMON_NAMES["imo"],
        "MMSI": COMMON_NAMES["mmsi"],
        "Flag": COMMON_NAMES["flag"],
        "Callsign": COMMON_NAMES["call_sign"],
        "AIS type": COMMON_NAMES['ais_type'],
        "Deadweight": COMMON_NAMES['dwt'],
        "Gross tonnage": COMMON_NAMES["gt"],
        "Year of build": COMMON_NAMES["build"],
        "Navigational status": COMMON_NAMES['navigation_status'],
        "Course": COMMON_NAMES['course'],
        "Speed": COMMON_NAMES['speed'],
        "MAX Speed": COMMON_NAMES['max_speed'],
        "Area": COMMON_NAMES['area'],
        "ETA": COMMON_NAMES['eta'],
        "Source": COMMON_NAMES['source'],
        "Destination": COMMON_NAMES['destination'],
        "Position": COMMON_NAMES['position_received'],
        "Status": COMMON_NAMES['status'],
    }
    
}
